#!/bin/bash

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
	echo "[PROTECT-MASTER: tried update \"master\" - FAIL]"
    exit 1
fi

echo "[PROTECT-MASTER: ok]"
exit 0